# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d7e17aa199fcf3bfbe0941f4fae099628ad5d6e946362adf7848b143fd60564ed950000569d9ad4ffd46a875dddc97ef7cb13a5043e4b9aacaf000dd79a71d

test:
  secret_key_base: b40e0db79be4bf45a040d211891cc8db6912e1a8618ec3906f8842c4ca61028c400be82de43f4c732e21572747e4eeb307dc9afeb43881c553fce5d94083a905

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
